### ISSUE TITLE
Fix resources.qld.gov.au font

### ISSUE THREAD

**Issue by nicholascar** [Kurrawong/qld-resources-prez-ui#1]
The font for the top-left text "resources.qld.gov.au" appears to be Lato on https://www.resources.qld.gov.au/ whereas it's ".SF NS" - a system font - on https://kurrawong.github.io/qld-resources-prez-ui/#/

**Comment by edmondchuc** [comment]
Fixed in https://github.com/Kurrawong/qld-resources-prez-ui/commit/1aa5d63f1c1dc8b720d21b57fd429d2216d813d0
