### ISSUE TITLE
Top blue bar hight wrong

### ISSUE THREAD

**Issue by nicholascar** [Kurrawong/qld-resources-prez-ui#2]
At https://www.resources.qld.gov.au/, top blue bar is 48px high, on https://kurrawong.github.io/qld-resources-prez-ui/#/ it's 45.4

**Comment by edmondchuc** [comment]
The top blue bar is 48px in height for me on a large desktop view.

![Screenshot 2023-03-27 at 10 33 59 am](https://user-images.githubusercontent.com/37032744/227815191-b0c3112f-1b2c-4c1c-83c2-09145d30e94d.png)

Are you able to take a screenshot from your side? Maybe the height changes based on the screen size or something.

**Comment by edmondchuc** [comment]
Top blue bar is 48px in deployed Prez at https://gsq-prez.dev.kurrawong.ai/.
