### ISSUE TITLE
Enhance main menu

### ISSUE THREAD

**Issue by nicholascar** [Kurrawong/qld-resources-prez-ui#3]
The Prez UI main menu looks like this:

![image](https://user-images.githubusercontent.com/7321872/227689601-6e448326-ae4c-4838-b21f-33f795c0ea37.png)

And Resources:

![image](https://user-images.githubusercontent.com/7321872/227689625-377dd7cc-3180-403e-90f8-24b34ba41f70.png)

* add a top orange border
* change the blue to match the Resources blue
* get rid of "Prez"
    * replace with a breadcrumbs that looks like the main site's: Home > Applications > Linked Data Server
    * "Applications" I've just made up, just make it text, not a link
* Make the prompt text for "Global Search" read "Linked Data Search"

**Comment by edmondchuc** [comment]
Prez in the dark background header has been removed. 

Breadcrumbs working correctly in upstream Prez UI.

The "Global Search" text change to "Linked Data Search" was rejected in upstream repo.
