### ISSUE TITLE
Footer updates

### ISSUE THREAD

**Issue by nicholascar** [Kurrawong/qld-resources-prez-ui#5]
* remove orange-topped grey area
* remove word "footer"
* Put Prez UI & Prez API info into bottom of main content area, not in a special footer section
    - technically this could be a footer but with the same colouring as the main text area
* "Contact Us" button should be orange

**Comment by edmondchuc** [comment]
Footer contact us button and footer heading text is fixed in https://github.com/Kurrawong/qld-resources-prez-ui/commit/1c20ee24fb66c4949be0b1732854c595e9207b9d.

**Comment by edmondchuc** [comment]
Current build is set to the latest commit in Prez UI by https://github.com/Kurrawong/qld-resources-prez-ui/commit/574cbb6ed6073bfd6efb37daf8d3e596c05d996d. Looks like Jamie has moved the Prez UI info to the side nav. Will work with Jamie to remove the grey Prez footer.

**Comment by edmondchuc** [comment]
This is no longer an issue in the latest deployment of GSQ's Prez. https://gsq-prez.dev.kurrawong.ai/
